-- Seed default users (passwords: admin123 and employee123)
-- These should be hashed in the application code
INSERT OR IGNORE INTO users (id, username, email, password, role, employee_id) VALUES
('1', 'admin', 'admin@example.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJqOeJqJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'admin', NULL),
('2', 'john_doe', 'john@example.com', '$2a$10$rOzJqJqJqJqJqJqJqJqJqOeJqJqJqJqJqJqJqJqJqJqJqJqJqJq', 'employee', '1');

-- Note: The password hashes above are placeholders. 
-- Real hashes will be generated by the application using bcrypt

